// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a personalized introduction for a visitor to Abdullah's portfolio.
 *
 * - generateIntro - A function that generates a personalized introduction.
 * - GenerateIntroInput - The input type for the generateIntro function.
 * - GenerateIntroOutput - The return type for the generateIntro function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateIntroInputSchema = z.object({
  visitorName: z.string().describe('The name of the visitor.'),
  visitorProfile: z
    .string()
    .describe(
      'A summary of the visitor profile, including their skills, experience, and interests.'
    ),
  portfolioContent: z.string().describe('The content of Abdullah\'s portfolio.'),
});
export type GenerateIntroInput = z.infer<typeof GenerateIntroInputSchema>;

const GenerateIntroOutputSchema = z.object({
  introduction: z
    .string()
    .describe('A personalized introduction for the visitor based on Abdullah\'s portfolio.'),
});
export type GenerateIntroOutput = z.infer<typeof GenerateIntroOutputSchema>;

export async function generateIntro(input: GenerateIntroInput): Promise<GenerateIntroOutput> {
  return generateIntroFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateIntroPrompt',
  input: {schema: GenerateIntroInputSchema},
  output: {schema: GenerateIntroOutputSchema},
  prompt: `You are an AI assistant that generates personalized introductions for visitors to Abdullah's portfolio.

  Based on the content of the portfolio and the visitor's profile, create a short and engaging introduction that highlights Abdullah's background and how it relates to the visitor's needs.

  Portfolio Content: {{{portfolioContent}}}
  Visitor Name: {{{visitorName}}}
  Visitor Profile: {{{visitorProfile}}}

  Introduction:`,
});

const generateIntroFlow = ai.defineFlow(
  {
    name: 'generateIntroFlow',
    inputSchema: GenerateIntroInputSchema,
    outputSchema: GenerateIntroOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
